/* eslint-disable react/prop-types */
import { useEffect, useMemo, useState } from 'react'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import { useAuth, useUser } from '@clerk/clerk-react'
import toast from 'react-hot-toast'
import { getFullName, profileToBookingFields } from '../lib/patientProfiles'
import { createAppointment, getAppointments, getProfiles, getServices, updateAppointment } from '../lib/recordsApi'
import { isSecretaryRole } from '../lib/bookings'
import DatabaseLoading from '../components/DatabaseLoading'
import { formatPrice } from '../components/ServicesManager'

const blank = { profileId: '', serviceId: '', dentistId: '', name: '', dateOfBirth: '', guardianContact: '', medicalIssue: '', emergencyLevel: 'low', duration: 30, date: '', time: '' }
const steps = ['Service', 'Dentist', 'Date & Time', 'Patient Details', 'Confirm']
const times = Array.from({ length: 18 }, (_, index) => { const minutes = 8 * 60 + index * 30; return `${String(Math.floor(minutes / 60)).padStart(2, '0')}:${String(minutes % 60).padStart(2, '0')}` })
const businessDay = (value) => { const day = new Date(`${value}T00:00:00`).getDay(); return day !== 0 && day !== 6 }

export default function ReservationPage() {
  const { user, isLoaded } = useUser(); const { getToken } = useAuth(); const navigate = useNavigate(); const [params] = useSearchParams(); const editId = params.get('edit')
  const [form, setForm] = useState(blank); const [services, setServices] = useState([]); const [profiles, setProfiles] = useState([]); const [step, setStep] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const service = useMemo(() => services.find((item) => item.id === form.serviceId), [services, form.serviceId])
  const dentist = service?.dentists.find((item) => item.id === form.dentistId)
  const role = user?.publicMetadata?.role || 'member'
  const set = (key, value) => setForm((previous) => ({ ...previous, [key]: value }))
  const load = async () => { setLoading(true); setError(''); try { const [serviceItems, profileItems] = await Promise.all([getServices(getToken), getProfiles(getToken)]); setServices(serviceItems.filter((item) => item.status === 'active')); setProfiles(profileItems) } catch (e) { setError(e.message || 'Unable to load booking options.') } finally { setLoading(false) } }
  useEffect(() => { if (isLoaded && user) load() }, [getToken, isLoaded, user])
  useEffect(() => { if (!editId || !user) return; getAppointments(getToken).then((items) => { const booking = items.find((item) => item.id === editId && item.userId === user.id); if (booking) setForm({ ...blank, ...booking }) }).catch(() => setError('Unable to load this appointment.')) }, [editId, getToken, user])
  const advance = () => {
    if (step === 1 && !service) return toast.error('Select a service first.')
    if (step === 2 && !dentist) return toast.error('Select a dentist.')
    if (step === 3 && (!form.date || !form.time || !businessDay(form.date) || new Date(`${form.date}T${form.time}`).getTime() <= Date.now())) return toast.error('Choose a future weekday appointment time.')
    if (step === 4 && (!form.profileId || form.medicalIssue.trim().length < 10)) return toast.error('Choose a patient profile and describe the reason for the visit.')
    setStep((value) => Math.min(5, value + 1))
  }
  const selectService = (item) => { setForm((previous) => ({ ...previous, serviceId: item.id, dentistId: '', duration: item.duration })); setStep(2) }
  const selectProfile = (id) => { const profile = profiles.find((item) => item.id === id); setForm((previous) => ({ ...previous, ...(profile ? profileToBookingFields(profile) : { profileId: '', name: '', dateOfBirth: '' }) })) }
  const submit = async () => { try { const booking = { ...form, id: editId || crypto.randomUUID(), duration: service.duration, status: isSecretaryRole(role) ? 'approved' : 'pending', requestedByRole: role }; if (editId) await updateAppointment(getToken, booking); else await createAppointment(getToken, booking); navigate('/booked') } catch (e) { toast.error(e.message || 'Unable to save appointment.'); if (/unavailable|cannot be booked/i.test(e.message)) { await load(); setStep(1) } } }
  if (!isLoaded || (user && loading)) return <div className="mx-auto max-w-2xl rounded-2xl bg-white p-6 shadow-sm"><DatabaseLoading label="Loading booking options…" className="py-0" /></div>
  if (!user) return <div className="mx-auto max-w-2xl rounded-2xl bg-white p-8 text-center shadow-sm"><h1 className="text-2xl font-semibold">Sign in to book an appointment</h1><Link to="/sign-in?redirect_url=/reservation" className="mt-5 inline-block rounded-full bg-slate-900 px-6 py-3 text-sm font-semibold text-white">Sign In</Link></div>
  if (error) return <div className="mx-auto max-w-2xl rounded-2xl border border-red-200 bg-red-50 p-6 text-red-700">{error}<button onClick={load} className="ml-3 font-semibold underline">Retry</button></div>
  return <div className="mx-auto w-full max-w-5xl px-2 py-4 sm:px-6 sm:py-8"><h1 className="text-2xl font-semibold text-slate-900 sm:text-3xl">{editId ? 'Edit Appointment' : 'Book an Appointment'}</h1><p className="mt-2 text-slate-600">Choose a service, its dentist, and a time that works for you.</p>
    <ol className="my-6 flex overflow-x-auto pb-2">{steps.map((label, index) => <li key={label} className="flex shrink-0 items-center text-xs sm:text-sm"><span className={`flex h-7 w-7 items-center justify-center rounded-full font-semibold ${step >= index + 1 ? 'bg-slate-900 text-white' : 'bg-slate-200 text-slate-500'}`}>{index + 1}</span><span className="ml-1.5 mr-3 whitespace-nowrap text-slate-600">{label}</span>{index < 4 && <span className="mr-3 h-px w-5 bg-slate-200" />}</li>)}</ol>
    <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-8">
      {step === 1 && <div><h2 className="text-xl font-semibold">Select a service</h2><p className="mt-1 text-sm text-slate-500">Only currently active services can be booked.</p>{services.length === 0 ? <p className="mt-6 rounded-xl border border-dashed border-slate-300 p-8 text-center text-slate-500">There are no active services available right now.</p> : <div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{services.map((item) => <article key={item.id} className="flex flex-col rounded-2xl border border-slate-200 p-5"><h3 className="font-semibold">{item.name}</h3><p className="mt-2 flex-1 text-sm text-slate-500">{item.description}</p><div className="mt-4 flex justify-between text-sm"><span>{item.duration} min</span><strong>{formatPrice(item.price)}</strong></div><button onClick={() => selectService(item)} className="mt-5 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white">Select</button></article>)}</div>}</div>}
      {step === 2 && <div><h2 className="text-xl font-semibold">Choose a dentist</h2><p className="mt-1 text-sm text-slate-500">{service.name} · {service.duration} minutes</p>{service.dentists.length ? <div className="mt-5 grid gap-3 sm:grid-cols-2">{service.dentists.map((item) => <button key={item.id} onClick={() => { set('dentistId', item.id); setStep(3) }} className={`rounded-xl border p-4 text-left font-semibold ${dentist?.id === item.id ? 'border-blue-600 bg-blue-50' : 'border-slate-200 hover:border-blue-300'}`}>{item.name}</button>)}</div> : <p className="mt-6 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">This service does not have an assigned dentist yet. Please choose another service.</p>}</div>}
      {step === 3 && <div className="max-w-xl"><h2 className="text-xl font-semibold">Date & Time</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="grid gap-1 text-sm font-medium">Date<input type="date" min={new Date().toISOString().slice(0, 10)} value={form.date} onChange={(e) => set('date', e.target.value)} className="rounded-xl border border-slate-200 px-3 py-3" /></label><label className="grid gap-1 text-sm font-medium">Time<select value={form.time} onChange={(e) => set('time', e.target.value)} className="rounded-xl border border-slate-200 px-3 py-3"><option value="">Choose a time</option>{times.map((time) => <option key={time}>{time}</option>)}</select></label></div><p className="mt-3 text-sm text-slate-500">Appointments are available Monday through Friday, 8:00 AM–5:00 PM.</p></div>}
      {step === 4 && <div className="max-w-xl"><h2 className="text-xl font-semibold">Patient Details</h2><div className="mt-5 space-y-4"><label className="grid gap-1 text-sm font-medium">Patient profile<select value={form.profileId} onChange={(e) => selectProfile(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-3"><option value="">Select a saved profile</option>{profiles.map((item) => <option key={item.id} value={item.id}>{getFullName(item)}</option>)}</select></label>{profiles.length === 0 && <p className="text-sm text-amber-700">Create a <Link to="/patients/create" className="font-semibold underline">patient profile</Link> before booking.</p>}<label className="grid gap-1 text-sm font-medium">Reason for visit<textarea value={form.medicalIssue} onChange={(e) => set('medicalIssue', e.target.value)} minLength="10" rows="4" className="rounded-xl border border-slate-200 px-3 py-3" placeholder="Describe symptoms or the reason for your visit" /></label></div></div>}
      {step === 5 && <div><h2 className="text-xl font-semibold">Confirm appointment</h2><dl className="mt-5 grid gap-3 rounded-xl bg-slate-50 p-5 text-sm sm:grid-cols-2"><Item label="Service" value={service.name} /><Item label="Price" value={formatPrice(service.price)} /><Item label="Dentist" value={dentist.name} /><Item label="Date & time" value={`${form.date} at ${form.time}`} /><Item label="Patient" value={form.name} /><Item label="Reason" value={form.medicalIssue} /></dl></div>}
      <div className="mt-8 flex justify-between gap-3">{step > 1 ? <button onClick={() => setStep((value) => value - 1)} className="rounded-xl border border-slate-300 px-5 py-3 text-sm font-semibold">Back</button> : <span />}{step < 5 ? <button onClick={advance} disabled={step === 1 && !services.length} className="rounded-xl bg-slate-900 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">Continue</button> : <button onClick={submit} className="rounded-xl bg-emerald-600 px-5 py-3 text-sm font-semibold text-white">Confirm booking</button>}</div>
    </section></div>
}
function Item({ label, value }) { return <div><dt className="text-slate-500">{label}</dt><dd className="mt-1 font-medium text-slate-900">{value}</dd></div> }
