import { useEffect, useState } from 'react'
import toast from 'react-hot-toast'
import { getClinicSettings, updateClinicSettings } from '../lib/recordsApi'

const days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
const defaults = { workingDays: [1, 2, 3, 4, 5], openingTime: '08:00', closingTime: '17:00', daysOff: [] }

export default function ClinicSettingsManager({ getToken }) {
  const [settings, setSettings] = useState(defaults); const [newDayOff, setNewDayOff] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false)
  useEffect(() => { getClinicSettings(getToken).then(setSettings).catch((error) => toast.error(error.message || 'Unable to load clinic settings.')).finally(() => setLoading(false)) }, [getToken])
  const toggleDay = (day) => setSettings((current) => ({ ...current, workingDays: current.workingDays.includes(day) ? current.workingDays.filter((item) => item !== day) : [...current.workingDays, day].sort() }))
  const addDayOff = () => { if (newDayOff && !settings.daysOff.includes(newDayOff)) setSettings((current) => ({ ...current, daysOff: [...current.daysOff, newDayOff].sort() })); setNewDayOff('') }
  const save = async (event) => { event.preventDefault(); setSaving(true); try { setSettings(await updateClinicSettings(getToken, settings)); toast.success('Clinic availability updated.') } catch (error) { toast.error(error.message || 'Unable to save clinic settings.') } finally { setSaving(false) } }
  return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm font-medium text-blue-600">Booking configuration</p><h2 className="mt-1 text-xl font-bold">Working hours & days off</h2><p className="mt-1 text-sm text-slate-500">These rules control the dates and times clients can choose.</p>{loading ? <p className="py-8 text-sm text-slate-500">Loading clinic settings…</p> : <form onSubmit={save} className="mt-5 space-y-5"><fieldset><legend className="text-sm font-medium">Working days</legend><div className="mt-2 flex flex-wrap gap-2">{days.map((day, index) => <label key={day} className={`cursor-pointer rounded-full border px-3 py-2 text-sm ${settings.workingDays.includes(index) ? 'border-blue-600 bg-blue-50 text-blue-700' : 'border-slate-200 text-slate-600'}`}><input className="sr-only" type="checkbox" checked={settings.workingDays.includes(index)} onChange={() => toggleDay(index)} />{day}</label>)}</div></fieldset><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1 text-sm font-medium">Opening time<input type="time" required value={settings.openingTime} onChange={(event) => setSettings((current) => ({ ...current, openingTime: event.target.value }))} className="rounded-xl border border-slate-200 px-3 py-2.5" /></label><label className="grid gap-1 text-sm font-medium">Closing time<input type="time" required value={settings.closingTime} onChange={(event) => setSettings((current) => ({ ...current, closingTime: event.target.value }))} className="rounded-xl border border-slate-200 px-3 py-2.5" /></label></div><div><label className="text-sm font-medium">Days off</label><div className="mt-2 flex gap-2"><input type="date" value={newDayOff} onChange={(event) => setNewDayOff(event.target.value)} className="rounded-xl border border-slate-200 px-3 py-2.5" /><button type="button" onClick={addDayOff} disabled={!newDayOff} className="rounded-xl border border-slate-300 px-4 text-sm font-semibold disabled:opacity-50">Add</button></div><div className="mt-3 flex flex-wrap gap-2">{settings.daysOff.length ? settings.daysOff.map((date) => <button type="button" key={date} onClick={() => setSettings((current) => ({ ...current, daysOff: current.daysOff.filter((item) => item !== date) }))} className="rounded-full bg-slate-100 px-3 py-1.5 text-sm text-slate-700">{date} ×</button>) : <p className="text-sm text-slate-500">No one-off closure dates.</p>}</div></div><button disabled={saving} className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{saving ? 'Saving…' : 'Save availability rules'}</button></form>}</section>
}
