/* eslint-disable react/prop-types */
import { useEffect, useRef, useState } from 'react'
import { useAuth } from '@clerk/clerk-react'
import { Edit3, LoaderCircle, Plus, ToggleLeft, ToggleRight, X } from 'lucide-react'
import toast from 'react-hot-toast'
import { createService, getServiceDentists, getServices, updateService } from '../lib/recordsApi'

const blank = () => ({ name: '', category: 'General Dentistry', duration: 30, price: 0, dentistIds: [], status: 'active', description: '' })
export const formatPrice = (price) => Number(price) === 0 ? 'Free' : `$${Number(price).toFixed(2)}`

export function ServicesManager({ embedded = false }) {
  const { getToken } = useAuth(); const [services, setServices] = useState([]); const [dentists, setDentists] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [editing, setEditing] = useState(null); const [saving, setSaving] = useState(false); const savingRef = useRef(false)
  const load = async () => { setLoading(true); setError(''); try { const [s, d] = await Promise.all([getServices(getToken), getServiceDentists(getToken)]); setServices(s); setDentists(d) } catch (e) { setError(e.message || 'Could not load services.') } finally { setLoading(false) } }
  useEffect(() => { load() }, [getToken])
  const save = async (item) => { if (savingRef.current) return; savingRef.current = true; setSaving(true); try { const saved = item.id ? await updateService(getToken, item) : await createService(getToken, item); setServices((all) => item.id ? all.map((x) => x.id === saved.id ? saved : x) : [...all, saved]); setEditing(null); toast.success(`Service ${item.id ? 'updated' : 'added'}`) } catch (e) { toast.error(e.message || 'Could not save service.') } finally { savingRef.current = false; setSaving(false) } }
  const toggle = (item) => save({ ...item, dentistIds: item.dentists.map((d) => d.id), status: item.status === 'active' ? 'inactive' : 'active' })
  return <section id="services" className={`${embedded ? 'mt-8 border-t border-slate-200 pt-8' : 'min-h-full bg-[#f8faff]'} text-slate-900`}><div className="mx-auto max-w-7xl px-4 py-6 sm:px-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-blue-600">Admin management</p><h1 className="mt-1 text-3xl font-bold">Services</h1><p className="mt-2 text-sm text-slate-500">Create services and assign the dentists who can provide them.</p></div><button onClick={() => setEditing(blank())} className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold text-white"><Plus size={18} />Add Service</button></div>
  {loading ? <div className="py-14 text-center text-slate-500"><LoaderCircle className="mx-auto mb-2 animate-spin text-blue-600" />Loading services…</div> : error ? <div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}<button onClick={load} className="ml-3 font-semibold underline">Retry</button></div> : services.length === 0 ? <div className="mt-5 rounded-xl border border-dashed border-slate-300 p-10 text-center text-sm text-slate-500">No services yet. Add the first bookable service.</div> : <div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{services.map((item) => <article key={item.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><div><h2 className="font-semibold">{item.name}</h2><p className="mt-1 text-xs text-slate-500">{item.category} · {item.duration} min</p></div><span className={`inline-flex min-h-8 shrink-0 items-center rounded-full px-3 py-1 text-xs font-semibold ${item.status === 'active' ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-600'}`}>Status: {item.status === 'active' ? 'Active' : 'Inactive'}</span></div><p className="mt-3 min-h-10 text-sm text-slate-600">{item.description}</p><p className="mt-3 font-semibold">{formatPrice(item.price)}</p><p className="mt-2 text-xs text-slate-500">Dentists: {item.dentists.map((d) => d.name).join(', ') || 'Unassigned'}</p><div className="mt-4 flex gap-2"><button onClick={() => setEditing({ ...item, dentistIds: item.dentists.map((d) => d.id) })} disabled={saving} className="inline-flex items-center gap-1 rounded-lg px-2.5 py-2 text-xs font-semibold text-blue-700 disabled:opacity-50"><Edit3 size={15} />Edit</button><button onClick={() => toggle(item)} disabled={saving} className="inline-flex items-center gap-1 rounded-lg px-2.5 py-2 text-xs font-semibold text-slate-700 disabled:opacity-50">{item.status === 'active' ? <ToggleRight size={16} /> : <ToggleLeft size={16} />}{item.status === 'active' ? 'Deactivate' : 'Activate'}</button></div></article>)}</div>}</div>{editing && <Modal item={editing} dentists={dentists} onClose={() => setEditing(null)} onSave={save} saving={saving} />}</section>
}

function Modal({ item, dentists, onClose, onSave, saving }) { const [data, setData] = useState(item); const set = (e) => setData((p) => ({ ...p, [e.target.name]: e.target.value })); const pick = (id) => setData((p) => ({ ...p, dentistIds: p.dentistIds.includes(id) ? p.dentistIds.filter((x) => x !== id) : [...p.dentistIds, id] })); return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/35 p-4" role="dialog" aria-modal="true"><form onSubmit={(e) => { e.preventDefault(); onSave({ ...data, duration: Number(data.duration), price: Number(data.price) }) }} className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-5 shadow-xl"><div className="flex justify-between"><div><h2 className="text-xl font-bold">{data.id ? 'Edit Service' : 'Add Service'}</h2><p className="text-sm text-slate-500">Saved directly to the booking catalog.</p></div><button type="button" disabled={saving} onClick={onClose}><X /></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Service name" name="name" value={data.name} onChange={set} /><Field label="Category" name="category" value={data.category} onChange={set} /><Field label="Duration (minutes)" name="duration" type="number" min="5" value={data.duration} onChange={set} /><Field label="Price (USD)" name="price" type="number" min="0" step="0.01" value={data.price} onChange={set} /><label className="grid gap-1 text-sm font-medium">Status<select name="status" value={data.status} onChange={set} className="rounded-xl border border-slate-200 px-3 py-2.5 font-normal"><option value="active">Active</option><option value="inactive">Inactive</option></select></label><fieldset className="sm:col-span-2"><legend className="text-sm font-medium">Assigned dentists</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{dentists.length ? dentists.map((d) => <label key={d.id} className="flex items-center gap-2 rounded-lg border border-slate-200 p-2.5 text-sm"><input type="checkbox" checked={data.dentistIds.includes(d.id)} onChange={() => pick(d.id)} />{d.name}</label>) : <p className="text-sm text-slate-500">No staff users are available.</p>}</div></fieldset><label className="grid gap-1 text-sm font-medium sm:col-span-2">Description<textarea name="description" value={data.description} onChange={set} required rows="3" className="rounded-xl border border-slate-200 px-3 py-2.5 font-normal" /></label></div><div className="mt-6 flex justify-end gap-3"><button type="button" disabled={saving} onClick={onClose}>Cancel</button><button disabled={saving} className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{saving ? 'Saving…' : 'Save service'}</button></div></form></div> }
function Field({ label, ...props }) { return <label className="grid gap-1 text-sm font-medium">{label}<input {...props} required className="rounded-xl border border-slate-200 px-3 py-2.5 font-normal" /></label> }
